package com.expeditionx.backend.service;

import com.expeditionx.backend.dto.MiscDTOs.*;
import com.expeditionx.backend.entity.*;
import com.expeditionx.backend.exception.ResourceNotFoundException;
import com.expeditionx.backend.ml.PackingListGenerator;
import com.expeditionx.backend.repository.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.stream.Collectors;

@Service
public class ToolkitService {
    private final PackingChecklistItemRepository packingRepo;
    private final TravelDocumentRepository docRepo;
    private final LocalEventRepository eventRepo;
    private final TripRepository tripRepo;
    private final PackingListGenerator packingGen;

    public ToolkitService(PackingChecklistItemRepository packingRepo, TravelDocumentRepository docRepo,
                          LocalEventRepository eventRepo, TripRepository tripRepo,
                          PackingListGenerator packingGen) {
        this.packingRepo = packingRepo;
        this.docRepo = docRepo;
        this.eventRepo = eventRepo;
        this.tripRepo = tripRepo;
        this.packingGen = packingGen;
    }

    public List<PackingItemResponse> getPackingChecklist(Long tripId) {
        List<PackingChecklistItem> items = packingRepo.findByTripIdOrderByCategoryAsc(tripId);
        if (items.isEmpty()) {
            // Auto-generate packing list
            Trip trip = tripRepo.findById(tripId)
                    .orElseThrow(() -> new ResourceNotFoundException("Trip", "id", tripId));
            items = packingGen.generate(trip);
            packingRepo.saveAll(items);
        }
        return items.stream().map(i -> new PackingItemResponse(
            i.getId(), i.getItemName(), i.getCategory(), i.isChecked(), i.isAutoGenerated()
        )).collect(Collectors.toList());
    }

    @Transactional
    public PackingItemResponse updatePackingItem(Long itemId, PackingItemUpdateRequest req) {
        PackingChecklistItem item = packingRepo.findById(itemId)
                .orElseThrow(() -> new ResourceNotFoundException("PackingItem", "id", itemId));
        if (req.checked() != null) item.setChecked(req.checked());
        if (req.itemName() != null) item.setItemName(req.itemName());
        packingRepo.save(item);
        return new PackingItemResponse(item.getId(), item.getItemName(), item.getCategory(), item.isChecked(), item.isAutoGenerated());
    }

    public List<DocumentResponse> getDocuments(Long tripId) {
        return docRepo.findByTripId(tripId).stream().map(d -> new DocumentResponse(
            d.getId(), d.getDocumentType().name(), d.getFileUrl(), d.getFileName(), d.getStatus().name()
        )).collect(Collectors.toList());
    }

    public DocumentResponse uploadDocument(Long tripId, Long userId, String docType, String fileUrl, String fileName) {
        Trip trip = tripRepo.findById(tripId).orElseThrow(() -> new ResourceNotFoundException("Trip", "id", tripId));
        TravelDocument doc = new TravelDocument();
        doc.setTrip(trip);
        doc.setUser(new User() {{ setId(userId); }});
        doc.setDocumentType(TravelDocument.DocType.valueOf(docType));
        doc.setFileUrl(fileUrl);
        doc.setFileName(fileName);
        doc.setStatus(TravelDocument.DocStatus.UPLOADED);
        doc = docRepo.save(doc);
        return new DocumentResponse(doc.getId(), doc.getDocumentType().name(), doc.getFileUrl(), doc.getFileName(), doc.getStatus().name());
    }

    public List<LocalEventResponse> getLocalEvents(String city, String fromDate, String toDate) {
        if (fromDate != null && toDate != null) {
            return eventRepo.findByCityContainingIgnoreCaseAndDateBetween(
                city, java.time.LocalDate.parse(fromDate), java.time.LocalDate.parse(toDate)
            ).stream().map(this::toEventResponse).collect(Collectors.toList());
        }
        return eventRepo.findByCityContainingIgnoreCase(city).stream()
                .map(this::toEventResponse).collect(Collectors.toList());
    }

    private LocalEventResponse toEventResponse(LocalEvent e) {
        return new LocalEventResponse(e.getId(), e.getName(), e.getCity(),
                e.getDate() != null ? e.getDate().toString() : null, e.getDescription());
    }
}
