package com.expeditionx.backend.entity;

import jakarta.persistence.*;

@Entity @Table(name = "packing_checklist_items")
public class PackingChecklistItem {
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY) private Long id;
    @ManyToOne(fetch = FetchType.LAZY) @JoinColumn(name = "trip_id") private Trip trip;
    private String itemName;
    private String category; // Clothing, Toiletries, Electronics, Documents, etc.
    private boolean checked = false;
    private boolean autoGenerated = false;

    public PackingChecklistItem() {}
    public Long getId() { return id; } public void setId(Long id) { this.id = id; }
    public Trip getTrip() { return trip; } public void setTrip(Trip t) { this.trip = t; }
    public String getItemName() { return itemName; } public void setItemName(String n) { this.itemName = n; }
    public String getCategory() { return category; } public void setCategory(String c) { this.category = c; }
    public boolean isChecked() { return checked; } public void setChecked(boolean c) { this.checked = c; }
    public boolean isAutoGenerated() { return autoGenerated; } public void setAutoGenerated(boolean a) { this.autoGenerated = a; }
}
