package com.expeditionx.backend.dto;

import java.util.List;
import java.util.Map;

// ===== MISC DTOs =====
public class MiscDTOs {

    // Chat
    public record ChatRequest(String message) {}
    public record ChatResponse(
        String reply, String intent, Object payload // payload can be place cards, cost data, etc.
    ) {}
    public record ChatHistoryItem(String message, String response, String intent, String timestamp) {}

    // Review
    public record CreateReviewRequest(Long placeId, Integer rating, String comment, List<String> photos) {}
    public record ReviewResponse(
        Long id, String userName, String userAvatar, String placeName, Integer rating,
        String comment, Double sentimentScore, String sentimentLabel,
        List<String> photos, Integer upvotes, String createdAt
    ) {}

    // Wishlist
    public record WishlistRequest(Long placeId) {}
    public record WishlistResponse(Long id, PlaceDTOs.PlaceResponse place, String addedAt) {}

    // Notification
    public record NotificationResponse(
        Long id, String type, String title, String message, boolean read, String createdAt
    ) {}
    public record MarkReadRequest(List<Long> ids) {}

    // Toolkit
    public record PackingItemResponse(Long id, String itemName, String category, boolean checked, boolean autoGenerated) {}
    public record PackingItemUpdateRequest(Boolean checked, String itemName) {}
    public record DocumentResponse(Long id, String documentType, String fileUrl, String fileName, String status) {}
    public record CurrencyConvertResponse(String from, String to, Double amount, Double converted, Double rate) {}
    public record LocalEventResponse(Long id, String name, String city, String date, String description) {}
    public record WeatherResponse(
        String city, Double temp, Double feelsLike, String description, String icon,
        Double humidity, Double windSpeed, List<MonthlyClimate> monthlyData
    ) {}
    public record MonthlyClimate(String month, Double avgTemp, Double rainfall, String recommendation) {}

    // Gamification
    public record GamificationResponse(Long userId, Integer xp, Integer level, List<String> badges) {}
    public record AwardXpRequest(Long userId, Integer xp, String reason) {}

    // Referral
    public record ReferralResponse(String referralCode, String referralLink, List<ReferralItem> referrals) {}
    public record ReferralItem(String email, String status, Double reward, String date) {}

    // User Profile
    public record UserProfileResponse(
        Long id, String name, String email, String avatarUrl, String role,
        boolean onboardingCompleted, String createdAt
    ) {}
    public record UpdateProfileRequest(String name, String avatarUrl) {}
    public record ChangePasswordRequest(String currentPassword, String newPassword) {}

    // Support
    public record SupportTicketRequest(String subject, String message) {}
    public record SupportTicketResponse(Long id, String subject, String message, String status, String createdAt) {}
    public record FaqItem(Long id, String question, String answer, String category) {}

    // Admin
    public record AnalyticsResponse(Map<String, Object> data) {}
}
