package com.expeditionx.backend.ml;

import com.expeditionx.backend.entity.PackingChecklistItem;
import com.expeditionx.backend.entity.Trip;
import org.springframework.stereotype.Component;

import java.time.temporal.ChronoUnit;
import java.util.*;

/**
 * Rule-based packing checklist generator.
 * Combines destination, weather, trip theme, and duration to suggest items.
 */
@Component
public class PackingListGenerator {

    private static final Map<String, List<String[]>> ESSENTIALS = Map.of(
        "Documents", new List[]{List.of(
            new String[]{"Passport/ID", "Documents"}, new String[]{"Tickets/Boarding Pass", "Documents"},
            new String[]{"Travel Insurance", "Documents"}, new String[]{"Hotel Confirmation", "Documents"},
            new String[]{"Emergency Contacts List", "Documents"}
        )}[0],
        "Toiletries", List.of(
            new String[]{"Toothbrush & Toothpaste", "Toiletries"}, new String[]{"Sunscreen SPF 50+", "Toiletries"},
            new String[]{"Deodorant", "Toiletries"}, new String[]{"Hand Sanitizer", "Toiletries"},
            new String[]{"Basic First Aid Kit", "Toiletries"}
        ),
        "Electronics", List.of(
            new String[]{"Phone Charger", "Electronics"}, new String[]{"Power Bank", "Electronics"},
            new String[]{"Earphones/Headphones", "Electronics"}, new String[]{"Camera", "Electronics"}
        )
    );

    private static final Map<String, List<String[]>> WEATHER_ITEMS = Map.of(
        "hot", List.of(
            new String[]{"Sunglasses", "Accessories"}, new String[]{"Hat/Cap", "Accessories"},
            new String[]{"Light Cotton Shirts (x3)", "Clothing"}, new String[]{"Shorts (x2)", "Clothing"},
            new String[]{"Sandals", "Footwear"}, new String[]{"Water Bottle", "Accessories"}
        ),
        "cold", List.of(
            new String[]{"Warm Jacket", "Clothing"}, new String[]{"Thermal Wear", "Clothing"},
            new String[]{"Gloves", "Accessories"}, new String[]{"Woolen Cap", "Accessories"},
            new String[]{"Boots", "Footwear"}, new String[]{"Hot Water Flask", "Accessories"}
        ),
        "rainy", List.of(
            new String[]{"Raincoat/Umbrella", "Accessories"}, new String[]{"Waterproof Bag", "Accessories"},
            new String[]{"Quick-Dry Clothing", "Clothing"}, new String[]{"Waterproof Shoes", "Footwear"}
        )
    );

    public List<PackingChecklistItem> generate(Trip trip) {
        List<PackingChecklistItem> items = new ArrayList<>();

        // Add essentials
        ESSENTIALS.values().forEach(list -> list.forEach(pair ->
            items.add(createItem(trip, pair[0], pair[1]))
        ));

        // Add weather-based items (default to "hot" for India)
        String weather = guessWeather(trip);
        WEATHER_ITEMS.getOrDefault(weather, WEATHER_ITEMS.get("hot")).forEach(pair ->
            items.add(createItem(trip, pair[0], pair[1]))
        );

        // Add duration-based extras
        long days = 3;
        if (trip.getStartDate() != null && trip.getEndDate() != null) {
            days = ChronoUnit.DAYS.between(trip.getStartDate(), trip.getEndDate());
        }
        if (days > 5) {
            items.add(createItem(trip, "Laundry Bag", "Accessories"));
            items.add(createItem(trip, "Extra Underwear Set", "Clothing"));
        }
        if (days > 10) {
            items.add(createItem(trip, "Travel Detergent", "Toiletries"));
            items.add(createItem(trip, "Neck Pillow", "Accessories"));
        }

        return items;
    }

    private String guessWeather(Trip trip) {
        if (trip.getDestinations() == null) return "hot";
        String dest = trip.getDestinations().toLowerCase();
        if (dest.contains("manali") || dest.contains("shimla") || dest.contains("ladakh")) return "cold";
        if (dest.contains("kerala") || dest.contains("goa") || dest.contains("mumbai")) return "rainy";
        return "hot";
    }

    private PackingChecklistItem createItem(Trip trip, String name, String category) {
        PackingChecklistItem item = new PackingChecklistItem();
        item.setTrip(trip);
        item.setItemName(name);
        item.setCategory(category);
        item.setAutoGenerated(true);
        return item;
    }
}
